<?php

require_once __DIR__.'/../bootstrap.php';

/**
 * Test class for Department.
 * Generated by PHPUnit on 2012-01-25 at 13:38:59.
 */
class DepartmentTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Department
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {    
        
        $this->object = new Department;
		
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetName().
     */
    public function testGetName()
    {
	    $name = 'BlaFusel';
        $this->object->setName($name);
		$this->assertEquals($name, $this->object->getName());
    }

    /**
     * @todo Implement testSetName().
     */
    public function testStore()
    {
	    global $entityManager;
        $name = 'BlaFusel21231233';
        $department = new Department();
		$department->setName($name);
        $entityManager->getConnection()->beginTransaction();
        $entityManager->persist($department);
        $entityManager->flush();
		
		$department_read = new Department();
		$department_read = $entityManager->getRepository('Department')
                         ->findOneBy(array('name' => $name));
						 
						 
		$this->assertEquals($department->getId(), $department_read->getId());
		$entityManager->getConnection()->rollback();

    }

    /**
     * @todo Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
